server:
  port: 3333

spring:
  application:
    name: api-gateway

zuul:
  prefix: /api
  routes:   abc:
      path: /wmsg/**
      service-id: welcomeapp

   xyz:
      path: /gmsg/**
      service-id: greetapp   