INSERT INTO STOCK_PRICE (STOCK_ID,COMPANY_NAME,STOCK_COST) VALUES(101,'BHEL',56.67);
INSERT INTO STOCK_PRICE (STOCK_ID,COMPANY_NAME,STOCK_COST) VALUES(102,'MRF',155.63);

INSERT INTO STOCK_PRICE (STOCK_ID,COMPANY_NAME,STOCK_COST) VALUES(103,'SBI',344.05);